### ISSUE TITLE
[Research]: React in ue5

### ISSUE THREAD

**Issue by Menzorg** [deep-foundation/deep-vision#1]
### Object, subject, context, hypotheses

Can react.js be rendered in ue5? Could it be interactive and reactive?

**Comment by CEHR2005** [comment]
- react.js be rendered in ue5?
Yes, react can be rendered and displayed in ue5 viewport.
- Could it be interactive and reactive?
Yes it could.

 Based on the research, 2 hypotheses were put forward that needed testing.

1) Interaction of react.js with VR.
2) The ability to display the react not in the viewport but on the physical plane within the project.
